//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Manager_Mobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Report_Manager_Mobile.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User or password wrong, try again..
        /// </summary>
        internal static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adress: .
        /// </summary>
        internal static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Report Manager Mobile.
        /// </summary>
        internal static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RISK ASSESSMENT AND ACTIVITIES.
        /// </summary>
        internal static string ARA {
            get {
                return ResourceManager.GetString("ARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 - Riscos Químicos.
        /// </summary>
        internal static string ARA1 {
            get {
                return ResourceManager.GetString("ARA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 . 1 - Presença de Gás.
        /// </summary>
        internal static string ARA1_1 {
            get {
                return ResourceManager.GetString("ARA1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 . 2 - Produtos Químicos.
        /// </summary>
        internal static string ARA1_2 {
            get {
                return ResourceManager.GetString("ARA1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 . 3 - Produtos de Limpeza.
        /// </summary>
        internal static string ARA1_3 {
            get {
                return ResourceManager.GetString("ARA1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 . 4 - Tintas / Solventes / Vernizes.
        /// </summary>
        internal static string ARA1_4 {
            get {
                return ResourceManager.GetString("ARA1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 1 . 5 - Monóxido de Carbono.
        /// </summary>
        internal static string ARA1_5 {
            get {
                return ResourceManager.GetString("ARA1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2 - Riscos Físicos.
        /// </summary>
        internal static string ARA2 {
            get {
                return ResourceManager.GetString("ARA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2 . 1 - Ruído excessivo.
        /// </summary>
        internal static string ARA2_1 {
            get {
                return ResourceManager.GetString("ARA2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2 . 2 - Vibrações excessivas.
        /// </summary>
        internal static string ARA2_2 {
            get {
                return ResourceManager.GetString("ARA2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 2 . 3 - Calor excessivo.
        /// </summary>
        internal static string ARA2_3 {
            get {
                return ResourceManager.GetString("ARA2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3 - Riscos Ergonômicos.
        /// </summary>
        internal static string ARA3 {
            get {
                return ResourceManager.GetString("ARA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3 . 1 - Posição inadequada.
        /// </summary>
        internal static string ARA3_1 {
            get {
                return ResourceManager.GetString("ARA3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3 . 2 - Manuseio de pesos.
        /// </summary>
        internal static string ARA3_2 {
            get {
                return ResourceManager.GetString("ARA3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 3 . 3 - Espaço insuficiente para trabalhar.
        /// </summary>
        internal static string ARA3_3 {
            get {
                return ResourceManager.GetString("ARA3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 - Riscos Biológicos.
        /// </summary>
        internal static string ARA4 {
            get {
                return ResourceManager.GetString("ARA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 . 1 - Água contaminada.
        /// </summary>
        internal static string ARA4_1 {
            get {
                return ResourceManager.GetString("ARA4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 . 2 - Animais mortos.
        /// </summary>
        internal static string ARA4_2 {
            get {
                return ResourceManager.GetString("ARA4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 . 3 - Esgotos.
        /// </summary>
        internal static string ARA4_3 {
            get {
                return ResourceManager.GetString("ARA4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 . 4 - Animais peçonhentos.
        /// </summary>
        internal static string ARA4_4 {
            get {
                return ResourceManager.GetString("ARA4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 4 . 5 - Enxame de insetos.
        /// </summary>
        internal static string ARA4_5 {
            get {
                return ResourceManager.GetString("ARA4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 - Riscos Ambientais.
        /// </summary>
        internal static string ARA5 {
            get {
                return ResourceManager.GetString("ARA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 . 1 - Vazamento de Gás.
        /// </summary>
        internal static string ARA5_1 {
            get {
                return ResourceManager.GetString("ARA5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 . 2 - Vazamento de odorante.
        /// </summary>
        internal static string ARA5_2 {
            get {
                return ResourceManager.GetString("ARA5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 . 3 - Desmatamento.
        /// </summary>
        internal static string ARA5_3 {
            get {
                return ResourceManager.GetString("ARA5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 . 4 - Contaminação do solo.
        /// </summary>
        internal static string ARA5_4 {
            get {
                return ResourceManager.GetString("ARA5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 . 5 - Vazamento de óleo / combustível.
        /// </summary>
        internal static string ARA5_5 {
            get {
                return ResourceManager.GetString("ARA5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 5 . 6 - Mortalidade de animais.
        /// </summary>
        internal static string ARA5_6 {
            get {
                return ResourceManager.GetString("ARA5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 - Riscos de Acidentes.
        /// </summary>
        internal static string ARA6 {
            get {
                return ResourceManager.GetString("ARA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 1 - Máquinas / equipamentos sem proteção.
        /// </summary>
        internal static string ARA6_1 {
            get {
                return ResourceManager.GetString("ARA6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 10 - Material / equipamento cortante.
        /// </summary>
        internal static string ARA6_10 {
            get {
                return ResourceManager.GetString("ARA6_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 11 - Condições meteorológicas.
        /// </summary>
        internal static string ARA6_11 {
            get {
                return ResourceManager.GetString("ARA6_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 12 - Queda.
        /// </summary>
        internal static string ARA6_12 {
            get {
                return ResourceManager.GetString("ARA6_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 13 - Iluminação.
        /// </summary>
        internal static string ARA6_13 {
            get {
                return ResourceManager.GetString("ARA6_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 14 - Incêndio / Explosão.
        /// </summary>
        internal static string ARA6_14 {
            get {
                return ResourceManager.GetString("ARA6.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 2 - Equipamento danificado.
        /// </summary>
        internal static string ARA6_2 {
            get {
                return ResourceManager.GetString("ARA6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 3 - Ferramenta inadequada.
        /// </summary>
        internal static string ARA6_3 {
            get {
                return ResourceManager.GetString("ARA6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 4 - Equipamento energizado.
        /// </summary>
        internal static string ARA6_4 {
            get {
                return ResourceManager.GetString("ARA6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 5 - Alta voltagem.
        /// </summary>
        internal static string ARA6_5 {
            get {
                return ResourceManager.GetString("ARA6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 6 - Fiação desencapada.
        /// </summary>
        internal static string ARA6_6 {
            get {
                return ResourceManager.GetString("ARA6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 7 - Cabos subterrâneos.
        /// </summary>
        internal static string ARA6_7 {
            get {
                return ResourceManager.GetString("ARA6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 8 - Material / equipamento aquecido.
        /// </summary>
        internal static string ARA6_8 {
            get {
                return ResourceManager.GetString("ARA6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 6 . 9 - Piso irregular / escorregadio / desnível.
        /// </summary>
        internal static string ARA6_9 {
            get {
                return ResourceManager.GetString("ARA6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 - Riscos Adicionais.
        /// </summary>
        internal static string ARA7 {
            get {
                return ResourceManager.GetString("ARA7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 1 - Trânsito intenso.
        /// </summary>
        internal static string ARA7_1 {
            get {
                return ResourceManager.GetString("ARA7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 2 - Viatura em local inadequado.
        /// </summary>
        internal static string ARA7_2 {
            get {
                return ResourceManager.GetString("ARA7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 3 - Sinalização insuficiente.
        /// </summary>
        internal static string ARA7_3 {
            get {
                return ResourceManager.GetString("ARA7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 4 - Vala profunda.
        /// </summary>
        internal static string ARA7_4 {
            get {
                return ResourceManager.GetString("ARA7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 5 - Interferências.
        /// </summary>
        internal static string ARA7_5 {
            get {
                return ResourceManager.GetString("ARA7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 6 - Terreno instável.
        /// </summary>
        internal static string ARA7_6 {
            get {
                return ResourceManager.GetString("ARA7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 7 - Roubo/ animal doméstico.
        /// </summary>
        internal static string ARA7_7 {
            get {
                return ResourceManager.GetString("ARA7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a 7 . 8 - Presença de escola / ponto de ônibus / hospital.
        /// </summary>
        internal static string ARA7_8 {
            get {
                return ResourceManager.GetString("ARA7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Costumer: .
        /// </summary>
        internal static string Costumer {
            get {
                return ResourceManager.GetString("Costumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No data avaliable.
        /// </summary>
        internal static string EmptyDataView {
            get {
                return ResourceManager.GetString("EmptyDataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Facility: .
        /// </summary>
        internal static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next.
        /// </summary>
        internal static string LoginNext {
            get {
                return ResourceManager.GetString("LoginNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Meter: .
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serial Number: .
        /// </summary>
        internal static string MeterSN {
            get {
                return ResourceManager.GetString("MeterSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NO.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not found..
        /// </summary>
        internal static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quit application?.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Save my credentials?.
        /// </summary>
        internal static string SaveCredentials {
            get {
                return ResourceManager.GetString("SaveCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SI: .
        /// </summary>
        internal static string ServiceNote {
            get {
                return ResourceManager.GetString("ServiceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Available.
        /// </summary>
        internal static string TabPageHeaderAvaliable {
            get {
                return ResourceManager.GetString("TabPageHeaderAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Completed.
        /// </summary>
        internal static string TabPageHeaderCompleted {
            get {
                return ResourceManager.GetString("TabPageHeaderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Settings.
        /// </summary>
        internal static string TabPageHeaderSettings {
            get {
                return ResourceManager.GetString("TabPageHeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a example@accellsolutions.com.
        /// </summary>
        internal static string UserExample {
            get {
                return ResourceManager.GetString("UserExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Warning.
        /// </summary>
        internal static string WarnignCaption {
            get {
                return ResourceManager.GetString("WarnignCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a YES.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
