//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report_Manager_Mobile.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Report_Manager_Mobile.Resources.Languages.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password wrong, try again..
        /// </summary>
        internal static string AccountError {
            get {
                return ResourceManager.GetString("AccountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress: .
        /// </summary>
        internal static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Manager Mobile.
        /// </summary>
        internal static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RISK ASSESSMENT AND ACTIVITIES.
        /// </summary>
        internal static string ARA {
            get {
                return ResourceManager.GetString("ARA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Riscos Químicos.
        /// </summary>
        internal static string ARA1 {
            get {
                return ResourceManager.GetString("ARA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 . 1 - Presença de Gás.
        /// </summary>
        internal static string ARA1_1 {
            get {
                return ResourceManager.GetString("ARA1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 . 2 - Produtos Químicos.
        /// </summary>
        internal static string ARA1_2 {
            get {
                return ResourceManager.GetString("ARA1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 . 3 - Produtos de Limpeza.
        /// </summary>
        internal static string ARA1_3 {
            get {
                return ResourceManager.GetString("ARA1_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 . 4 - Tintas / Solventes / Vernizes.
        /// </summary>
        internal static string ARA1_4 {
            get {
                return ResourceManager.GetString("ARA1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 . 5 - Monóxido de Carbono.
        /// </summary>
        internal static string ARA1_5 {
            get {
                return ResourceManager.GetString("ARA1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Riscos Físicos.
        /// </summary>
        internal static string ARA2 {
            get {
                return ResourceManager.GetString("ARA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 . 1 - Ruído excessivo.
        /// </summary>
        internal static string ARA2_1 {
            get {
                return ResourceManager.GetString("ARA2_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 . 2 - Vibrações excessivas.
        /// </summary>
        internal static string ARA2_2 {
            get {
                return ResourceManager.GetString("ARA2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 . 3 - Calor excessivo.
        /// </summary>
        internal static string ARA2_3 {
            get {
                return ResourceManager.GetString("ARA2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Riscos Ergonômicos.
        /// </summary>
        internal static string ARA3 {
            get {
                return ResourceManager.GetString("ARA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 . 1 - Posição inadequada.
        /// </summary>
        internal static string ARA3_1 {
            get {
                return ResourceManager.GetString("ARA3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 . 2 - Manuseio de pesos.
        /// </summary>
        internal static string ARA3_2 {
            get {
                return ResourceManager.GetString("ARA3_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 . 3 - Espaço insuficiente para trabalhar.
        /// </summary>
        internal static string ARA3_3 {
            get {
                return ResourceManager.GetString("ARA3_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Riscos Biológicos.
        /// </summary>
        internal static string ARA4 {
            get {
                return ResourceManager.GetString("ARA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 . 1 - Água contaminada.
        /// </summary>
        internal static string ARA4_1 {
            get {
                return ResourceManager.GetString("ARA4_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 . 2 - Animais mortos.
        /// </summary>
        internal static string ARA4_2 {
            get {
                return ResourceManager.GetString("ARA4_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 . 3 - Esgotos.
        /// </summary>
        internal static string ARA4_3 {
            get {
                return ResourceManager.GetString("ARA4_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 . 4 - Animais peçonhentos.
        /// </summary>
        internal static string ARA4_4 {
            get {
                return ResourceManager.GetString("ARA4_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 . 5 - Enxame de insetos.
        /// </summary>
        internal static string ARA4_5 {
            get {
                return ResourceManager.GetString("ARA4_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 - Riscos Ambientais.
        /// </summary>
        internal static string ARA5 {
            get {
                return ResourceManager.GetString("ARA5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 . 1 - Vazamento de Gás.
        /// </summary>
        internal static string ARA5_1 {
            get {
                return ResourceManager.GetString("ARA5_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 . 2 - Vazamento de odorante.
        /// </summary>
        internal static string ARA5_2 {
            get {
                return ResourceManager.GetString("ARA5_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 . 3 - Desmatamento.
        /// </summary>
        internal static string ARA5_3 {
            get {
                return ResourceManager.GetString("ARA5_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 . 4 - Contaminação do solo.
        /// </summary>
        internal static string ARA5_4 {
            get {
                return ResourceManager.GetString("ARA5_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 . 5 - Vazamento de óleo / combustível.
        /// </summary>
        internal static string ARA5_5 {
            get {
                return ResourceManager.GetString("ARA5_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 . 6 - Mortalidade de animais.
        /// </summary>
        internal static string ARA5_6 {
            get {
                return ResourceManager.GetString("ARA5_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 - Riscos de Acidentes.
        /// </summary>
        internal static string ARA6 {
            get {
                return ResourceManager.GetString("ARA6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 1 - Máquinas / equipamentos sem proteção.
        /// </summary>
        internal static string ARA6_1 {
            get {
                return ResourceManager.GetString("ARA6_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 10 - Material / equipamento cortante.
        /// </summary>
        internal static string ARA6_10 {
            get {
                return ResourceManager.GetString("ARA6_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 11 - Condições meteorológicas.
        /// </summary>
        internal static string ARA6_11 {
            get {
                return ResourceManager.GetString("ARA6_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 12 - Queda.
        /// </summary>
        internal static string ARA6_12 {
            get {
                return ResourceManager.GetString("ARA6_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 13 - Iluminação.
        /// </summary>
        internal static string ARA6_13 {
            get {
                return ResourceManager.GetString("ARA6_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 14 - Incêndio / Explosão.
        /// </summary>
        internal static string ARA6_14 {
            get {
                return ResourceManager.GetString("ARA6.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 2 - Equipamento danificado.
        /// </summary>
        internal static string ARA6_2 {
            get {
                return ResourceManager.GetString("ARA6_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 3 - Ferramenta inadequada.
        /// </summary>
        internal static string ARA6_3 {
            get {
                return ResourceManager.GetString("ARA6_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 4 - Equipamento energizado.
        /// </summary>
        internal static string ARA6_4 {
            get {
                return ResourceManager.GetString("ARA6_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 5 - Alta voltagem.
        /// </summary>
        internal static string ARA6_5 {
            get {
                return ResourceManager.GetString("ARA6_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 6 - Fiação desencapada.
        /// </summary>
        internal static string ARA6_6 {
            get {
                return ResourceManager.GetString("ARA6_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 7 - Cabos subterrâneos.
        /// </summary>
        internal static string ARA6_7 {
            get {
                return ResourceManager.GetString("ARA6_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 8 - Material / equipamento aquecido.
        /// </summary>
        internal static string ARA6_8 {
            get {
                return ResourceManager.GetString("ARA6_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 . 9 - Piso irregular / escorregadio / desnível.
        /// </summary>
        internal static string ARA6_9 {
            get {
                return ResourceManager.GetString("ARA6_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 - Riscos Adicionais.
        /// </summary>
        internal static string ARA7 {
            get {
                return ResourceManager.GetString("ARA7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 1 - Trânsito intenso.
        /// </summary>
        internal static string ARA7_1 {
            get {
                return ResourceManager.GetString("ARA7_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 2 - Viatura em local inadequado.
        /// </summary>
        internal static string ARA7_2 {
            get {
                return ResourceManager.GetString("ARA7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 3 - Sinalização insuficiente.
        /// </summary>
        internal static string ARA7_3 {
            get {
                return ResourceManager.GetString("ARA7_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 4 - Vala profunda.
        /// </summary>
        internal static string ARA7_4 {
            get {
                return ResourceManager.GetString("ARA7_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 5 - Interferências.
        /// </summary>
        internal static string ARA7_5 {
            get {
                return ResourceManager.GetString("ARA7_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 6 - Terreno instável.
        /// </summary>
        internal static string ARA7_6 {
            get {
                return ResourceManager.GetString("ARA7_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 7 - Roubo/ animal doméstico.
        /// </summary>
        internal static string ARA7_7 {
            get {
                return ResourceManager.GetString("ARA7_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 . 8 - Presença de escola / ponto de ônibus / hospital.
        /// </summary>
        internal static string ARA7_8 {
            get {
                return ResourceManager.GetString("ARA7_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string ARANo {
            get {
                return ResourceManager.GetString("ARANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ARAYes {
            get {
                return ResourceManager.GetString("ARAYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costumer: .
        /// </summary>
        internal static string Costumer {
            get {
                return ResourceManager.GetString("Costumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data avaliable.
        /// </summary>
        internal static string EmptyDataView {
            get {
                return ResourceManager.GetString("EmptyDataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorCaption {
            get {
                return ResourceManager.GetString("ErrorCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility: .
        /// </summary>
        internal static string Facility {
            get {
                return ResourceManager.GetString("Facility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use last saved presets.
        /// </summary>
        internal static string LatestSettings {
            get {
                return ResourceManager.GetString("LatestSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string LoginNext {
            get {
                return ResourceManager.GetString("LoginNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter: .
        /// </summary>
        internal static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number: .
        /// </summary>
        internal static string MeterSN {
            get {
                return ResourceManager.GetString("MeterSN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter Type.
        /// </summary>
        internal static string MeterType {
            get {
                return ResourceManager.GetString("MeterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string NoUser {
            get {
                return ResourceManager.GetString("NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit application?.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save my credentials?.
        /// </summary>
        internal static string SaveCredentials {
            get {
                return ResourceManager.GetString("SaveCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SI: .
        /// </summary>
        internal static string ServiceNote {
            get {
                return ResourceManager.GetString("ServiceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string TabPageHeaderAvaliable {
            get {
                return ResourceManager.GetString("TabPageHeaderAvaliable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        internal static string TabPageHeaderCompleted {
            get {
                return ResourceManager.GetString("TabPageHeaderCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string TabPageHeaderSettings {
            get {
                return ResourceManager.GetString("TabPageHeaderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to example@accellsolutions.com.
        /// </summary>
        internal static string UserExample {
            get {
                return ResourceManager.GetString("UserExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarnignCaption {
            get {
                return ResourceManager.GetString("WarnignCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
